import { collection, query, where, getDocs, orderBy } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { Calendar, User, ArrowRight, Loader2 } from 'lucide-react';
import { formatDate } from '../lib/utils';
import { Link } from 'react-router-dom';
import { handleFirestoreError } from '../lib/errorHandler';

import { SectionHeader } from './SectionHeader';

interface Post {
  id: string;
  title: string;
  description: string;
  image: string;
  author: string;
  date: any;
  category: string;
}

export function ContentGrid({ category, title }: { category: string, title: string }) {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);

  // Split title: first word white, rest blue
  const words = title.split(' ');
  const whiteText = words[0];
  const blueText = words.slice(1).join(' ');

  useEffect(() => {
    async function fetchPosts() {
      try {
        const collectionMap: Record<string, string> = {
          Blog: 'blogs',
          Stories: 'stories',
          News: 'news'
        };
        const collectionName = collectionMap[category] || category.toLowerCase();
        const colRef = collection(db, collectionName);
        const q = query(colRef, orderBy('date', 'desc'));
        const snapshot = await getDocs(q);
        const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Post));
        setPosts(data);
      } catch (err) {
        handleFirestoreError(err, 'list', category.toLowerCase());
      } finally {
        setLoading(false);
      }
    }
    fetchPosts();
  }, [category]);

  return (
    <div className="pt-32 pb-24 px-4 max-w-7xl mx-auto">
      <SectionHeader 
        whiteText={whiteText} 
        blueText={blueText} 
        description="Discover deep insights, stories, and the latest updates generated by our expert AI system."
        className="mb-16"
      />

      {loading ? (
        <div className="flex flex-col items-center justify-center py-24 gap-4">
          <Loader2 className="w-10 h-10 text-blue-500 animate-spin" />
          <span className="text-slate-500 font-medium tracking-wide">Fetching excellence...</span>
        </div>
      ) : posts.length === 0 ? (
        <div className="text-center py-24 glass-card">
          <p className="text-slate-500 italic">No {category.toLowerCase()} available yet. Check back soon!</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
          {posts.map((post, i) => (
            <motion.div
              key={post.id}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="flex flex-col h-full group"
            >
              <div className="aspect-[16/10] overflow-hidden relative rounded-2xl mb-6 shadow-2xl shadow-black/40">
                <img 
                  src={post.image || 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800'} 
                  alt={post.title} 
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                />
                <div className="absolute top-4 left-4">
                  <span className="px-3 py-1 bg-brand-blue/90 backdrop-blur-sm rounded-full text-[10px] font-black uppercase tracking-widest text-white shadow-lg">
                    {post.category}
                  </span>
                </div>
              </div>
              <div className="flex flex-col flex-grow space-y-4">
                <div className="flex items-center gap-4 text-[10px] font-black uppercase tracking-widest text-slate-500">
                  <span className="flex items-center gap-1.5"><Calendar className="w-3 h-3 text-brand-blue" /> {formatDate(post.date?.toDate?.() || post.date)}</span>
                  <span className="flex items-center gap-1.5"><User className="w-3 h-3 text-brand-blue" /> {post.author}</span>
                </div>
                <h3 className="text-2xl font-bold font-serif line-clamp-2 leading-tight group-hover:text-brand-blue transition-colors text-white">{post.title}</h3>
                <p className="text-slate-400 text-sm line-clamp-3 leading-relaxed flex-grow font-medium">{post.description}</p>
                <Link to={`/${category.toLowerCase()}/${post.id}`} className="inline-flex items-center gap-2 text-brand-blue font-black text-[10px] uppercase tracking-[0.2em] pt-4 group/link">
                  Detailed Report
                  <ArrowRight className="w-4 h-4 transition-transform group-hover/link:translate-x-1" />
                </Link>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
